[package]
name = "generative-art"
version = "0.1.0"
authors = ["Weslen Guerreiro <weslenng@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.23.8"
num-complex = "0.3.0"
